[2024-02-10T15:31:20.996+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T15:31:10.076733+00:00 [queued]>
[2024-02-10T15:31:21.017+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T15:31:10.076733+00:00 [queued]>
[2024-02-10T15:31:21.018+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T15:31:21.057+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-02-10 15:31:10.076733+00:00
[2024-02-10T15:31:21.068+0000] {standard_task_runner.py:60} INFO - Started process 182 to run task
[2024-02-10T15:31:21.074+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'send_email_task', 'manual__2024-02-10T15:31:10.076733+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp65xrtuat']
[2024-02-10T15:31:21.082+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask send_email_task
[2024-02-10T15:31:21.192+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T15:31:10.076733+00:00 [running]> on host 407ed8c69d77
[2024-02-10T15:31:21.697+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T15:31:10.076733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T15:31:10.076733+00:00'
[2024-02-10T15:31:21.713+0000] {etl_dag.py:187} INFO - Tipo de datos temp: float64
[2024-02-10T15:31:21.714+0000] {etl_dag.py:191} INFO - min temp: 5.0
[2024-02-10T15:31:21.715+0000] {etl_dag.py:194} INFO - max temp: 30.0
[2024-02-10T15:31:21.728+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_dag.py:202: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rows_to_notify.loc[df_transformed['temp'] < min_temperature, 'limite'] = min_temperature

[2024-02-10T15:31:21.733+0000] {etl_dag.py:208} INFO - Filas a notificar:
[2024-02-10T15:31:21.734+0000] {etl_dag.py:209} INFO -   country                                          name  temp  limite
1      GS  South Georgia and the South Sandwich Islands  2.57     5.0
[2024-02-10T15:31:23.745+0000] {etl_dag.py:245} ERROR - 'NoneType' object has no attribute 'encode'
[2024-02-10T15:31:23.746+0000] {etl_dag.py:246} ERROR - Error al enviar el correo electrÃ³nico.
[2024-02-10T15:31:23.746+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T15:31:23.761+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=send_email_task, execution_date=20240210T153110, start_date=20240210T153120, end_date=20240210T153123
[2024-02-10T15:31:23.821+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T15:31:23.866+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
